name: Deploy to GitHub Pages
env:
  PUBLISH_DIR: portfolio-aro/bin/Release/net6.0/publish/wwwroot

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish .NET Core Project
        run: dotnet publish portfolio-aro/portfolio-aro.csproj -c Release --nologo
        
      - name: List Full Publish Directory Contents
        run: ls -R $PUBLISH_DIR

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /portfolio-aro/

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
