name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # Use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 6.0
      - name: Moving to the right directory
        run: cd portfolio-aro
          
      - name: Publish .NET Core Project
        run: dotnet publish portfolio-aro.csproj -c Release -o release --nologo
          
