name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0

      - name: Publish .NET Core Project
        run: dotnet publish portfolio-aro/portfolio-aro.csproj -c Release -o release --nologo
